In [1]:
# Jupyter notebook for testing some functions in crystal analyser

In [2]:
import numpy as np
import numpy.linalg as la

In [3]:
from Mol2Reader import Mol2Reader

In [4]:
# Testing Plane
from Plane import Plane
%matplotlib qt
xugleq = Mol2Reader('../../data/CSD/mol2_supercells/YAPWAP.mol2').create_supercell()
mol = xugleq.molecules[0]
plane = mol.plane
coordinates = np.vstack([x.atomic_coordinates for x in mol.atoms])
x_min = min(coordinates[:,0])
x_max = max(coordinates[:,0])
y_min = min(coordinates[:,1])
y_max = max(coordinates[:,1])
# Test plot
ax = plane.plot(x_min=x_min,x_max=x_max,y_min=y_min,y_max=y_max)
ax = mol.plot(ax)
# Test project
for atom in mol.atoms:
    atom.atomic_coordinates = plane.project(atom.atomic_coordinates)
mol.plot()

[-20.27429433  -3.993734    -2.76886548]
[[-20.2367  -3.3188  -5.6796]]
[-0.02791757 -0.01314362  0.00712732]
[[-19.9037  -3.1676  -4.2707]]
[ 0.00665952  0.00313531 -0.00170017]
[[-19.2261  -4.1905  -3.5971]]
[ 0.02534758  0.01193367 -0.0064712 ]
[[-18.9507  -3.992   -2.2504]]
[ 0.04480883  0.02109605 -0.01143963]
[[-18.2409  -5.0288  -1.4094]]
[ 0.0502231   0.02364509 -0.01282189]
[[-19.9539  -1.9289  -2.2405]]
[ 0.01806274  0.00850396 -0.00461139]
[[-20.279   -2.0158  -3.5846]]
[ 2.93736345e-04  1.38291396e-04 -7.49904902e-05]
[[-19.1582  -5.6925  -0.6358]]
[-1.05891216 -0.49853701  0.27033884]
[[-17.6745  -5.9809  -2.2182]]
[ 0.30249849  0.14241662 -0.07722745]
[[-18.9653  -4.9877  -4.0433]]
[ 0.0248748   0.01171109 -0.0063505 ]
[[-17.5451  -4.5977  -0.8347]]
[ 0.6346372   0.2987879  -0.16202202]
[[-20.2086  -1.1449  -1.7685]]
[ 0.01332794  0.00627481 -0.0034026 ]
[[-20.7426  -1.312   -4.0233]]
[-0.01544311 -0.00727063  0.00394261]
[[-20.5085  -3.4326  -6.7868]]
[-0.06110802 -0.028

<Axes3DSubplot:>

In [5]:
plane.vector_angle(plane.unit_normal())

1.5707963267948966